functionality:
  name: make_additional_files
  description: ""
  arguments:
    - name: "--input"
      type: file
    - name: "--output"
      type: file
      direction: output
  resources:
    - type: python_script
      path: script.py
    - path: /src/shuji_suzuki/ss_opm
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        pypi:
          - numpy
          - pandas
          - scipy
          - scikit-learn
          - pyarrow
          - tables
